/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/model-broker/wrangler.jsonc --include-runtime=false apps/model-broker/worker-configuration.d.ts` (hash: 16ef7c8739f09dfd63b6ff9aeafac33c)
interface __BaseEnv_Env {
  AI: Ai;
  AI_GATEWAY_ID: "roundhouse-v2-development";
  ROUTING_MODEL: "openai/gpt-5.6-luna";
  ROUTING_ROUTES: '{"qualify":{"provider":"openai","model":"openai/gpt-5.6-luna","protocol":"openai-responses","thinkingLevel":"high"},"investigate":{"provider":"openai","model":"openai/gpt-5.6-terra","protocol":"openai-responses","thinkingLevel":"high"},"plan":{"provider":"openai","model":"openai/gpt-5.6-sol","protocol":"openai-responses","thinkingLevel":"max"},"implement":{"provider":"openai","model":"openai/gpt-5.6-terra","protocol":"openai-responses","thinkingLevel":"max"},"review-holistic":{"provider":"anthropic","model":"anthropic/claude-opus-5","protocol":"anthropic-messages","thinkingLevel":"max"},"review-security":{"provider":"moonshotai","model":"moonshotai/kimi-k3","protocol":"openai-completions","thinkingLevel":"max"},"review-data":{"provider":"openai","model":"openai/gpt-5.6-sol","protocol":"openai-responses","thinkingLevel":"max"}}';
  ROUTING_REASONING_EFFORT: "high";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
