/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/model-broker/wrangler.jsonc --include-runtime=false apps/model-broker/worker-configuration.d.ts` (hash: c91193d85d8b45f11ba172fd451bf88e)
interface __BaseEnv_Env {
  AI: Ai;
  AI_GATEWAY_ID: "roundhouse-v2-development";
  ROUTING_MODEL: "openai/gpt-5.6-sol";
  ROUTING_REASONING_EFFORT: "low";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
