/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/control-plane/wrangler.jsonc --include-runtime=false apps/control-plane/worker-configuration.d.ts` (hash: 200641a3af6dbd3fd7d347a6c9b25e60)
interface __BaseEnv_Env {
  BACKUP_BUCKET: R2Bucket;
  DB: D1Database;
  RUN_WAKEUPS: Queue;
  CONVERSATION_TURNS: Queue;
  CALLBACK_SIGNING_SECRET?: SecretsStoreSecret;
  ROUNDHOUSE_GITHUB_CLIENT_SECRET?: SecretsStoreSecret;
  ARTIFACTS: Artifacts;
  BROWSER: BrowserRun;
  ARTIFACTS_NAMESPACE: "roundhouse-v2-production" | "roundhouse-v2-development";
  ARTIFACTS_REMOTE_ORIGIN:
    | "https://00000000000000000000000000000000.artifacts.cloudflare.net"
    | "https://07ff5b32b60ae3e5d613b90ddde90069.artifacts.cloudflare.net";
  CONTROL_PLANE_ORIGIN:
    | "https://roundhouse-prod-control-plane.replace-me.workers.dev"
    | "https://roundhouse-v2-control-plane.default-07f.workers.dev";
  PUBLIC_ORIGIN:
    "https://roundhouse.rm-rf.rip" | "https://roundhouse-dev.rm-rf.rip";
  GITHUB_APP_ID: "9999999" | "4281837";
  GITHUB_CLIENT_ID: "Iv000000000000000000" | "Iv23liaPflwJhKpGfxvB";
  GITHUB_START_COMMAND: "/roundhouse start" | "/roundhouse-dev start";
  SANDBOX_TRANSPORT: "rpc";
  ATTEMPT_SANDBOXES:
    | DurableObjectNamespace /* RoundhouseRuntimeSandbox from roundhouse-v2-runtime-host-production */
    | DurableObjectNamespace /* RoundhouseRuntimeSandbox from roundhouse-v2-runtime-host */;
  MODEL_BROKER:
    | Fetcher /* roundhouse-v2-model-broker-production */
    | Fetcher /* roundhouse-v2-model-broker */;
  ATTEMPT_EXECUTIONS: Workflow<
    Parameters<
      import("./src/index").AttemptExecutionWorkflow["run"]
    >[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface ProductionEnv {
    BACKUP_BUCKET: R2Bucket;
    DB: D1Database;
    RUN_WAKEUPS: Queue;
    CONVERSATION_TURNS: Queue;
    CALLBACK_SIGNING_SECRET: SecretsStoreSecret;
    ROUNDHOUSE_GITHUB_CLIENT_SECRET: SecretsStoreSecret;
    ARTIFACTS: Artifacts;
    BROWSER: BrowserRun;
    ARTIFACTS_NAMESPACE: "roundhouse-v2-production";
    ARTIFACTS_REMOTE_ORIGIN: "https://00000000000000000000000000000000.artifacts.cloudflare.net";
    CONTROL_PLANE_ORIGIN: "https://roundhouse-prod-control-plane.replace-me.workers.dev";
    PUBLIC_ORIGIN: "https://roundhouse.rm-rf.rip";
    GITHUB_APP_ID: "9999999";
    GITHUB_CLIENT_ID: "Iv000000000000000000";
    GITHUB_START_COMMAND: "/roundhouse start";
    SANDBOX_TRANSPORT: "rpc";
    ATTEMPT_SANDBOXES: DurableObjectNamespace /* RoundhouseRuntimeSandbox from roundhouse-v2-runtime-host-production */;
    MODEL_BROKER: Fetcher /* roundhouse-v2-model-broker-production */;
    ATTEMPT_EXECUTIONS: Workflow<
      Parameters<
        import("./src/index").AttemptExecutionWorkflow["run"]
      >[0]["payload"]
    >;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "ARTIFACTS_NAMESPACE"
      | "ARTIFACTS_REMOTE_ORIGIN"
      | "CONTROL_PLANE_ORIGIN"
      | "PUBLIC_ORIGIN"
      | "GITHUB_APP_ID"
      | "GITHUB_CLIENT_ID"
      | "GITHUB_START_COMMAND"
      | "SANDBOX_TRANSPORT"
    >
  > {}
}
declare module "*.js" {
  const value: string;
  export default value;
}
