/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/control-plane/wrangler.jsonc --include-runtime=false apps/control-plane/worker-configuration.d.ts` (hash: 42038131905e820bd04864e9880d2665)
interface __BaseEnv_Env {
  DB: D1Database;
  RUN_WAKEUPS: Queue;
  ARTIFACTS: Artifacts;
  ARTIFACTS_NAMESPACE: "roundhouse-v2-development";
  ARTIFACTS_REMOTE_ORIGIN: "https://07ff5b32b60ae3e5d613b90ddde90069.artifacts.cloudflare.net";
  CONTROL_PLANE_ORIGIN: "https://roundhouse-v2-control-plane.default-07f.workers.dev";
  GITHUB_APP_ID: "4281837";
  GITHUB_APP_INSTALLATION_ID: "146147681";
  GITHUB_START_COMMAND: "/roundhouse-dev start";
  ATTEMPT_CONTAINERS: DurableObjectNamespace<
    import("./src/index").RoundhouseAttemptContainer
  >;
  MODEL_BROKER: Fetcher /* roundhouse-v2-model-broker */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "RoundhouseAttemptContainer";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
