/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/control-plane/wrangler.jsonc --include-runtime=false apps/control-plane/worker-configuration.d.ts` (hash: 58bfb416535991a0186e0e7f0b877329)
interface __BaseEnv_Env {
  BACKUP_BUCKET: R2Bucket;
  DB: D1Database;
  RUN_WAKEUPS: Queue;
  ARTIFACTS: Artifacts;
  BROWSER: BrowserRun;
  ARTIFACTS_NAMESPACE: "roundhouse-v2-development";
  ARTIFACTS_REMOTE_ORIGIN: "https://07ff5b32b60ae3e5d613b90ddde90069.artifacts.cloudflare.net";
  CONTROL_PLANE_ORIGIN: "https://roundhouse-v2-control-plane.default-07f.workers.dev";
  PUBLIC_ORIGIN: "https://roundhouse-dev.rm-rf.rip";
  GITHUB_APP_ID: "4281837";
  GITHUB_START_COMMAND: "/roundhouse-dev start";
  SANDBOX_TRANSPORT: "rpc";
  BACKUP_BUCKET_NAME: "roundhouse-v2-development-workspaces";
  CLOUDFLARE_R2_ACCOUNT_ID: "07ff5b32b60ae3e5d613b90ddde90069";
  ATTEMPT_SANDBOXES: DurableObjectNamespace<
    import("./src/index").RoundhouseAttemptSandbox
  >;
  MODEL_BROKER: Fetcher /* roundhouse-v2-model-broker */;
  ATTEMPT_EXECUTIONS: Workflow<
    Parameters<
      import("./src/index").AttemptExecutionWorkflow["run"]
    >[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "RoundhouseAttemptSandbox";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "ARTIFACTS_NAMESPACE"
      | "ARTIFACTS_REMOTE_ORIGIN"
      | "CONTROL_PLANE_ORIGIN"
      | "PUBLIC_ORIGIN"
      | "GITHUB_APP_ID"
      | "GITHUB_START_COMMAND"
      | "SANDBOX_TRANSPORT"
      | "BACKUP_BUCKET_NAME"
      | "CLOUDFLARE_R2_ACCOUNT_ID"
    >
  > {}
}
